language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - pkg-config
    - libcairo2-dev
    - libexpat1-dev
    - libgtk2.0-dev

script: bash -ex .travis-opam.sh
env:
  - OPAM_SWITCH=system
  - OPAM_SWITCH=4.02.2
  - OPAM_SWITCH=4.03.0
  - OPAM_SWITCH=4.04.0
